DROP DATABASE IF EXISTS data;
CREATE DATABASE data DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci;

USE data;

CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(300) NOT NULL,
	mail varchar(30) NOT NULL
);

CREATE TABLE notes (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	note_name VARCHAR(50) NOT NULL UNIQUE,
	user_id  VARCHAR(50) NOT NULL,
    note VARCHAR(9000) NOT NULL,
    public BOOLEAN NOT NULL
);

CREATE TABLE encrypted_notes (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	note_name VARCHAR(50) NOT NULL UNIQUE,
    note VARCHAR(9000) NOT NULL,
	password VARCHAR(300) NOT NULL
);

CREATE TABLE files (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id VARCHAR(50) NOT NULL,
	file_path VARCHAR(100) NOT NULL
);

CREATE TABLE fails (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ip VARCHAR(100) NOT NULL,
	fail_date datetime not null
);

